"""Add pending_notifications table

Revision ID: 2d0213647834
Revises: 7bd5caedf749
Create Date: 2026-02-16 09:58:31.467514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0213647834'
down_revision = '7bd5caedf749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_notifications_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_pending_notifications_notification_type'))

    op.drop_table('pending_notifications')
    # ### end Alembic commands ###
