"""Add equipment table

Revision ID: fe564f1c4920
Revises: 2e0d6d8be171
Create Date: 2026-02-15 08:05:02.729389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe564f1c4920'
down_revision = '2e0d6d8be171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=200), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_source', sa.String(length=200), nullable=True),
    sa.Column('acquisition_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('warranty_expiration', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_name'))
        batch_op.drop_index(batch_op.f('ix_equipment_area_id'))

    op.drop_table('equipment')
    # ### end Alembic commands ###
